%YAML:1.0
image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [975.356025, 0.000000, 608.861038, 0.000000, 975.110604, 368.761697, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [0.035122, -0.037097, -0.001608, -0.005216, 0.000000]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [983.484497, 0.000000, 601.777429, 0.000000, 0.000000, 989.472961, 367.557667, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
